apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: web
spec:
  routes:
    - match:
        http:
          pathExact: /
      destination:
        service: api
        namespace: api
        requestTimeout: 3s
        numRetries: 5
        retryOnConnectFailure: true
        retryOn: ['connect-failure','refused-stream','unavailable','cancelled','retriable-4xx','5xx']
